CREATE TABLE trainers (
                         id BIGINT UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                         first_name VARCHAR(20) NOT NULL,
                         middle_name VARCHAR(20),
                         last_name VARCHAR(20) NOT NULL,
                         photo VARCHAR(200),
                         description TEXT NOT NULL,
                         PRIMARY KEY (id)
);