CREATE TABLE trainings (
                          id BIGINT UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                          title VARCHAR(50) NOT NULL,
                          description TEXT NOT NULL,
                          photo VARCHAR(200),
                          is_individual BOOLEAN DEFAULT FALSE,
                          PRIMARY KEY (id)
);